export { default as Scene } from "./Scene"
export { default as Ground } from "./Ground"
export { default as Box } from "./Box"
export { default as Sphere } from "./Sphere"
export { default as HUD, HUDStat } from "./HUD"
export { default as PlayerController } from "./PlayerController"
export { CustomShaderMaterial, NEON_FRAG, NOISE_FRAG, WATER_FRAG } from "./ShaderMaterial"
export { ProceduralTerrain, ProceduralPlanet } from "./ProceduralMesh"
export { default as SpriteSheet } from "./SpriteSheet"
export { useProceduralTexture, drawCheckerboard, drawNoise, drawGradient, drawBricks } from "./TextureGen"
export { default as ParticleSystem, PARTICLE_PRESETS } from "./ParticleSystem"
export type { ParticleConfig, ParticleSystemProps } from "./ParticleSystem"
export { default as GLTFModel, preloadModel } from "./GLTFModel"
export type { GLTFModelProps } from "./GLTFModel"
// PostProcessing requires @react-three/postprocessing (not installed by default).
// Import directly when needed: import PostProcessing from "./components/PostProcessing"
// export { default as PostProcessing } from "./PostProcessing"
export { default as CustomShader, VOLUMETRIC_FOG_FRAG, OCEAN_FRAG, OCEAN_VERT } from "./CustomShader"
export type { CustomShaderProps } from "./CustomShader"
